# -*- coding: utf-8 -*-
"""Temario canónico OPE Médico de Urgencia Hospitalaria — Aragón.
Numeración granular reconstruida a partir de los docx oficiales y de los ids
observados en los bancos enriquecidos (MUok). Grupo: comun (1-40) / especifico (41-109).
"""

TEMAS = {
    # ---------------- PARTE COMÚN (1-40) ----------------
    1: "Constitución Española de 1978: La protección de la salud en la Constitución. Estatuto de Autonomía de Aragón.",
    2: "Competencias en salud recogidas en el Estatuto de Autonomía. Las Cortes de Aragón. El Gobierno de Aragón.",
    3: "El texto refundido de la Ley del Estatuto Básico del Empleado Público (RDL 5/2015): Deberes del empleado público y código de conducta.",
    4: "Representación, participación y negociación colectiva.",
    5: "El régimen jurídico de la protección de datos de carácter personal: Disposiciones generales. Principios de la protección de datos.",
    6: "Protección de datos: Derechos de las personas. Responsable y Encargado del Tratamiento.",
    7: "Ley 39/2015 del Procedimiento Administrativo Común: Ámbito de aplicación y principios generales.",
    8: "Los interesados en el procedimiento administrativo. Cómputo de plazos. Revisión de actos en vía administrativa: Revisión de oficio y recursos administrativos.",
    9: "Ley 14/1986 General de Sanidad. Ley 6/2002 de Salud de Aragón. Principios generales, estructura, contenidos.",
    10: "Ley 16/2003 de cohesión y calidad del Sistema Nacional de Salud. Principios generales, estructura, contenidos.",
    11: "Ley 44/2003 de Ordenación de las Profesiones Sanitarias. Ámbito de aplicación, contenidos.",
    12: "Ley 41/2002, básica reguladora de la autonomía del paciente y de derechos y obligaciones en materia de información y documentación clínica.",
    13: "Ley 9/2013 de Autoridad de Profesionales del Sistema Sanitario y de Servicios Sociales Públicos de Aragón.",
    14: "Ley 55/2003 del Estatuto Marco de personal Estatutario de los Servicios de Salud (I). Principios generales, estructura, contenidos.",
    15: "Clasificación del personal estatutario. Derechos y deberes. Adquisición y pérdida de la condición de personal estatutario.",
    16: "Provisión de plazas, selección y promoción interna. Movilidad del personal.",
    17: "Ley 55/2003 del Estatuto Marco de personal Estatutario de los Servicios de Salud (II). Retribuciones.",
    18: "Jornada de trabajo, permisos y licencias. Situaciones del personal estatutario.",
    19: "Régimen disciplinario. Modelo de Carrera Profesional en Aragón. Ley 53/1984 de incompatibilidades: Principios generales, ámbito de aplicación.",
    20: "La igualdad de oportunidades entre mujeres y hombres en Aragón: Disposiciones generales.",
    21: "Prevención y Protección Integral a las Mujeres Víctimas de Violencia en Aragón: Disposiciones Generales.",
    22: "La identidad y expresión de género e igualdad social y no discriminación en la Comunidad Autónoma de Aragón: Disposiciones Generales.",
    23: "La diversidad cultural y lucha contra la discriminación: Plan Integral para la Gestión de la Diversidad de Aragón 2018-2021.",
    24: "El sistema sanitario. Niveles asistenciales. Organización de los servicios sanitarios en Aragón.",
    25: "Estructura del Departamento de Sanidad de Aragón y del Servicio Aragonés de la Salud. Los Sectores sanitarios.",
    26: "Metodología de la Investigación: El método científico. Diseño de un proyecto de investigación. Estadística aplicada a los estudios de Medicina.",
    27: "El método epidemiológico. Epidemiología descriptiva: tipos de estudios, tasas e indicadores. Epidemiología analítica: tipos de estudios.",
    28: "Riesgo relativo, riesgo atribuible y Odds Ratio. Sesgos.",
    29: "Estudios experimentales. Ensayos clínicos. Ética de la investigación clínica. Validez de métodos diagnósticos: sensibilidad, especificidad, valor predictivo positivo.",
    30: "Evaluación de Tecnologías Sanitarias: Procedimientos de evaluación. Cartera de Servicios del Sistema Nacional de Salud.",
    31: "Procedimiento de actualización de la Cartera de Servicios del sistema de Salud de Aragón.",
    32: "Práctica basada en la evidencia. Variabilidad en la práctica médica. Búsqueda y valoración de evidencias.",
    33: "Aplicación de las evidencias a la toma de decisiones clínicas. Guías clínicas. Proyecto Guía-Salud.",
    34: "La seguridad del paciente. Gestión de riesgos. Principales problemas para la seguridad del paciente en el hospital.",
    35: "Estrategias para la mejora de la seguridad del paciente.",
    36: "Uso Racional del Medicamento. Criterios de selección de medicamentos. Equivalentes terapéuticos. Indicadores de calidad de prescripción.",
    37: "Evaluación y mejora de la calidad. Modelos de Gestión de la Calidad. Diseño de un programa de calidad.",
    38: "Principios fundamentales de la bioética: aplicación a la asistencia sanitaria. La relación médico-paciente, el consentimiento informado.",
    39: "Los comités de Bioética. La ética en la investigación clínica.",
    40: "Gobierno clínico. La implicación de los profesionales en el funcionamiento de las instituciones sanitarias.",
    # ---------------- PARTE ESPECÍFICA (41-109) ----------------
    41: "Soporte vital básico y avanzado en el adulto y en el niño. Protocolos de actuación. Desfibrilación externa semiautomática.",
    42: "Soporte vital avanzado en el paciente politraumatizado. Shock hipovolémico.",
    43: "Secuencia rápida de intubación. Analgesia, sedación y relajación muscular. Manejo en urgencias de la vía aérea difícil.",
    44: "Fármacos en urgencias vitales. Fluidoterapia en urgencias.",
    45: "Dolor torácico agudo. Etiología. Valoración, diagnóstico y normas de actuación en urgencias.",
    46: "Síndrome coronario agudo. Código infarto en la CCAA de Aragón.",
    47: "Arritmias cardiacas. Taquiarritmias auriculares y ventriculares: extrasistolia, TPSV, flutter, fibrilación auricular, taquicardia y fibrilación ventricular.",
    48: "Bradiarritmias. Bloqueos auriculoventriculares. Diagnóstico y tratamiento.",
    49: "Insuficiencia cardíaca aguda. Edema agudo de pulmón. Actitud ante la insuficiencia cardiaca crónica descompensada.",
    50: "Shock. Concepto y etiología del shock. Valoración, diagnóstico y tratamiento en urgencias.",
    51: "Síncope. Concepto y etiología del síncope. Valoración, diagnóstico y tratamiento en urgencias.",
    52: "Otras urgencias cardiovasculares: Urgencia/Emergencia hipertensiva. Síndrome aórtico agudo. Pericarditis aguda. Taponamiento cardiaco. Isquemia arterial aguda periférica.",
    53: "Disnea aguda. Diagnóstico diferencial. Insuficiencia respiratoria aguda.",
    54: "Enfermedad pulmonar obstructiva crónica. Reagudización de la EPOC. Valoración y tratamiento en urgencias.",
    55: "Asma bronquial. Agudización asmática. Valoración y tratamiento urgente.",
    56: "Tromboembolismo pulmonar. Trombosis venosa profunda. Valoración y tratamiento urgente.",
    57: "Hemoptisis. Valoración, diagnóstico y actuación en urgencias.",
    58: "Derrame pleural. Neumotórax espontáneo. Valoración, diagnóstico y actitud terapéutica.",
    59: "Neumonía adquirida en la comunidad. Neumonía nosocomial. Valoración, diagnóstico y tratamiento.",
    60: "Dolor abdominal agudo. Diagnóstico diferencial.",
    61: "Hemorragia digestiva alta. Hemorragia digestiva baja. Valoración, diagnóstico y actitud terapéutica.",
    62: "Ictericia. Colecistitis aguda. Cólico biliar. Colangitis aguda. Fracaso hepático agudo. Encefalopatía hepática aguda. Ascitis.",
    63: "Pancreatitis aguda. Valoración, diagnóstico y tratamiento urgente.",
    64: "Oclusión y suboclusión intestinal. Apendicitis aguda. Diagnóstico y manejo inicial.",
    65: "Síndrome diarreico agudo. Diagnóstico diferencial. Actitud terapéutica.",
    66: "Cefalea aguda. Coma. Diagnóstico diferencial y actitud terapéutica urgente.",
    67: "Crisis epilépticas. Tratamiento urgente de la crisis convulsiva.",
    68: "Accidente cerebrovascular agudo. Código ictus en la CCAA de Aragón.",
    69: "Síndrome meníngeo. Encefalitis. Absceso cerebral. Valoración y tratamiento urgente.",
    70: "Alteraciones del equilibrio ácido-base. Trastornos hidroelectrolíticos. Valoración, diagnóstico y tratamiento urgente.",
    71: "Diabetes mellitus: Descompensación hiperglucémica hiperosmolar no cetósica. Cetoacidosis diabética. Hiperglucemia aislada. Hipoglucemia.",
    72: "Pautas de insulina en el paciente hospitalizado en urgencias. Diabetes mellitus en situaciones especiales.",
    73: "Crisis tirotóxica. Crisis addisoniana. Crisis mixedematosa. Valoración y tratamiento urgente.",
    74: "Alteraciones de la hemostasia. Anticoagulación. Problemas trasfusionales y hemoderivados.",
    75: "Insuficiencia renal aguda. Diagnóstico y actitud terapéutica urgente. Manejo del paciente con insuficiencia renal crónica grave en urgencias.",
    76: "Cólico nefrítico. Litiasis renoureteral. Retención aguda de orina. Uropatía obstructiva. Hematuria. Síndrome escrotal agudo.",
    77: "Infección de vías urinarias: Cistitis. Uretritis. Prostatitis. Pielonefritis aguda. Actitud diagnóstica y tratamiento en urgencias.",
    78: "Enfermedad hipertensiva grave en el embarazo. Hemorragias en la gestación. Metrorragia.",
    79: "Enfermedad inflamatoria pélvica. Vulvovaginitis. Anticoncepción de emergencia. Complicaciones agudas de métodos anticonceptivos.",
    80: "Atención inicial del niño traumatizado. Convulsiones, fiebre, laringitis, bronquiolitis, bronquitis, crisis asmática y neumonía en el niño.",
    81: "Síndrome febril del paciente adulto no inmunodeprimido. Valoración y actuación en urgencias. Resistencia bacteriana a antimicrobianos.",
    82: "Sepsis. Valoración del paciente séptico. Normas de actuación. Shock séptico y fracaso multiorgánico. Código sepsis.",
    83: "Infecciones en el paciente inmunodeprimido, características especiales y manejo urgente.",
    84: "Valoración y actitud en urgencias ante las infecciones en el paciente con síndrome de inmunodeficiencia adquirida.",
    85: "Tuberculosis. Botulismo. Tétanos. Rabia. Fiebre en el paciente procedente del trópico. Actuación en urgencias.",
    86: "Traumatismo craneoencefálico. Traumatismo torácico. Valoración y tratamiento en urgencias.",
    87: "Fracturas, luxaciones y esguinces de extremidades. Valoración, diagnóstico y tratamiento en urgencias.",
    88: "Fracturas y luxaciones de pelvis y columna vertebral. Valoración, diagnóstico y tratamiento en urgencias.",
    89: "Valoración y tratamiento de las heridas. Traumatismos tendinosos, vasculares y nerviosos. Quemaduras. Síndrome de aplastamiento.",
    90: "Sinusitis. Faringoamigdalitis. Laringitis. Otitis. Epistaxis. Sordera súbita. Procesos agudos odontológicos. Celulitis cervicofaciales. Síndrome vertiginoso.",
    91: "Exploración oftalmológica básica. Diagnóstico diferencial del ojo rojo. Pérdida brusca de visión. Valoración, diagnóstico y tratamiento en urgencias.",
    92: "Crisis de ansiedad. Agitación psicomotriz. Psicosis agudas. Síndrome confusional agudo. Valoración, diagnóstico y tratamiento en urgencias.",
    93: "Depresión e intento suicida. Trastornos de la conducta alimentaria. Su abordaje en urgencias.",
    94: "Dolor agudo. Dolor crónico reagudizado. Dolor oncológico. Manejo en urgencias.",
    95: "Compresión medular y síndrome de vena cava superior en el paciente oncológico.",
    96: "Cuidados paliativos en urgencias.",
    97: "Aproximación inicial al paciente anciano en urgencias: Valoración clínica, funcional, mental y socioambiental.",
    98: "Lesiones por agentes físicos y ambientales. Lesiones por electricidad y rayos. Hipotermia.",
    99: "Hipertermia: golpe de calor, hipertermia maligna, síndrome neuroléptico maligno. Diagnóstico y tratamiento en urgencias.",
    100: "Intoxicaciones agudas. Valoración y tratamiento general.",
    101: "Principales intoxicaciones: Etílica. Psicofármacos. Drogas de abuso. Analgésicos. Caústicos. Monóxido de carbono. Insecticidas. Setas. Otras.",
    102: "Mordeduras. Picaduras. Urticaria. Angioedema. Anafilaxia. Valoración y tratamiento en urgencias.",
    103: "Técnicas diagnóstico-terapéuticas: Cateterización de vías venosas centrales (yugular, subclavia, femoral) y periféricas. Vía intraósea.",
    104: "Marcapasos transcutáneo. Cricotiroidotomía. Toracocentesis. Drenaje pleural. Paracentesis. Punción lumbar. Artrocentesis. Cardioversión eléctrica.",
    105: "Ventilación mecánica no invasiva en urgencias.",
    106: "Medicina urgente y ecografía: Protocolo FAST. Punciones vasculares ecodirigidas.",
    107: "Organización de los servicios de urgencias hospitalarios. Sistemas de triaje. Los SUH en situaciones de catástrofes.",
    108: "Coordinación con otros servicios. Transporte urgente interhospitalario. Indicadores de calidad en los servicios de urgencias hospitalarios.",
    109: "Manual de organización y funcionamiento de los Servicios de Urgencia hospitalarios de la Comunidad Autónoma de Aragón.",
}

def grupo(tema_id):
    if tema_id is None or tema_id <= 0:
        return "sin_clasificar"
    return "comun" if tema_id <= 40 else "especifico"
